### ISSUE TITLE
Describe ruby gems

### ISSUE THREAD

**Issue by martinmosegaard** [Praqma/praqma-rnd#22]
Link to bundler application guide. Mention why gems are awesome.

**Comment by buep** [comment]
Is this some research you have to do? As in i need to learn and figure out the above?

**Comment by martinmosegaard** [comment]
No, it's based on slack input. In case it will be useful for someone. If we want an actual usecase first, this should be closed for now.

**Comment by buep** [comment]
I'm thinking that praqma-rnd exist for work we have to do... so if you're writing a blog post on how to do bundler and gems it fit well.
Also if you want to form a small simple project around defining good practices.

But if it is just knowledge sharing I think it should go to our blog posts.

Then again, praqma-rnd is my intention this way... but we might settle for something else.

**Comment by buep** [comment]
And it was meant for all of us to have a place to create an issue for research work, because obviously we don't do any work without an issue :-)

**Comment by martinmosegaard** [comment]
I will close this - I am not writing a blog post, I don't have work to do related to Ruby gems. For people wanting to learn, the Internet is already a pretty helpful place to get started with Ruby gems.

FWIW, I started here: http://bundler.io/v1.13/guides/creating_gem.html
