### ISSUE TITLE
Jenkins setup 

### ISSUE THREAD

**Issue by timea** [Praqma/praqma-rnd#29]
Create a locally run Jenkins to avoid polluting our production Jenkins.

Use Jenkins as Code.

**Comment by timea** [comment]
Done, local jenkins as code is up and running.

**Comment by buep** [comment]
How can I then reproduce your research or demonstrate the setup for a customer? Where is the Jenkins?

**Comment by timea** [comment]
The deliverable of this project will be some Job DSL and pipeline scripts, so you can try it on any Jenkins. As we are moving from ours, I did not want to create confusion, rather just use jenkins as code locally.

**Comment by buep** [comment]
okay, but it is a small task size, so I would expect to get access to the jenkins-as-code repo you made already now?

**Comment by timea** [comment]
I do understand what you mean, Bue. I have our default jenkins as code running locally on my machine. You have access to the code of that in our Praqma repo. It was intended to be local, as our jenkins is moving. If you want to see the jobs I have played with(the model is not done as per the drawing, was working on getting the artifact copying to work), I can commit the jenkins-backup/jobs folder.

**Comment by buep** [comment]
I just need running code and a very easy way to start and run the same jobs you created... this do involve I clone a git repository you made somehow :-)
If you're not working on this more for example, someone else needs to be able to continue exactly where you left of...
so seedjobs, pipeline-scripts ore what needs to be committed somewhere so I can start it from scratch.

**Comment by timea** [comment]
Yes. So I will commit that one folder with an MD file about how to spin up jenkins, where to put this folder to make it work and where to pick up the work. I will make a task for it, as this task was about something else ;).
