### ISSUE TITLE
Update the milestone

### ISSUE THREAD

**Issue by lakruzz** [Praqma/praqma-rnd#39]
@buep 

We have [a milestone that is 4 months overdue](https://github.com/Praqma/praqma-rnd/milestone/3).

Can we take the issues back to the backlog or update the date -

**Comment by buep** [comment]
Yes because the codemines stopped working on it... I still think the "project" defined by the milestone is relevant, so I removed the date from the milestone to keep track of this little collection of issues that forms a project.
Alternatively we could use a tag?

**Comment by lakruzz** [comment]
Tag or Milestone - either works fine :+1:
