### ISSUE TITLE
Gather material for Sikuli/Jenkins blogpost

### ISSUE THREAD

**Issue by MichaelDepner** [Praqma/praqma-rnd#40]
Seems like it's possible to install Sikuli on a Jenkins Windows slave and do UI automation. A Sikuli blogpost would be a lot more fun if you could write it from a "do it with Jenkins" perspective.

Poke around on a Windows slave, figure out if it's possible to set up Sikuli and trigger it through a normal Jenkins job.

Result will be either material for a proper blogpost on the subject, or a writeup on why it wasn't possible.

**Comment by buep** [comment]
@MichaelMadsen if you create an issues and starts working on it... remember it must belong to a milestone that makes sense - else it pops up in my filter.

**Comment by MichaelDepner** [comment]
@buep Sorry about that, I'll remember it next time :)

**Comment by buep** [comment]
no problem....

**Comment by MichaelDepner** [comment]
It is indeed possible to run Sikuli on Jenkins. It's not pretty, but GUI never really is. Slave has to run via cmd and not as a windows service so a desktop is allocated. A remote desktop connection has to be kept open by installing vnc and having it connect to itself.

There's an example test running on a Windows slave here: http://code.praqma.net/ci/view/test/job/test_sikuli_on_nightcrawler_michael/

I've also made a short video showing Sikuli in action https://www.youtube.com/watch?v=mdM2BVbjA-w

There is definitely enough material to publish it as a blogpost (referenced issue above).
