### ISSUE TITLE
Pile up pipeline support resources

### ISSUE THREAD

**Issue by praqma-thi** [Praqma/praqma-rnd#7]
Build a knowledge repository:
The official dev guide
The discussion on ProjectAction
Replacing constructors with databound setters
Anything relevant about supporting Pipeline

**Comment by praqma-thi** [comment]
DevGuide
https://github.com/jenkinsci/pipeline-plugin/blob/master/DEVGUIDE.md

Project Actions
https://jenkins.io/blog/2016/05/25/update-plugin-for-pipeline/

Relevant video
https://www.youtube.com/watch?v=azyv183Ua6U

**Comment by buep** [comment]
Agreed that this is just collecting resources things and taking notes as we go.
WE will use for the blog post #9

**Comment by Andrey9kin** [comment]
Jenkins World 2016 - No, You Shouldn't Do That! Lessons from Using Pipeline https://www.youtube.com/watch?v=lLZwTMFf9GI

**Comment by praqma-thi** [comment]
I think we got pipeline support down by now :)
